# Generated by Django 5.2.4 on 2025-07-27 08:57

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='providers', related_query_name='provider', to='travels.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='ward',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', default=1, on_delete=django.db.models.deletion.PROTECT, to='travels.ward'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', related_query_name='place', to='travels.province'),
        ),
        migrations.AlterField(
            model_name='place',
            name='ward',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='province', chained_model_field='province', on_delete=django.db.models.deletion.PROTECT, to='travels.ward'),
        ),
    ]
