# Generated by Django 5.2.4 on 2025-07-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_provider_province_provider_ward_alter_place_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
