# Generated by Django 5.2.4 on 2025-07-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_location_payment_provider_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', related_query_name='message', to='travels.conversation'),
        ),
    ]
