# Generated by Django 5.2.4 on 2025-07-24 15:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_user_avatar_alter_image_url_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=ckeditor.fields.RichTextField(default='Chưa có mô tả!'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
