# Generated by Django 5.2.4 on 2025-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
