# Generated by Django 5.2.4 on 2025-07-27 15:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_provider_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
