# Generated by Django 5.2.4 on 2025-07-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_province_remove_place_location_district_ward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='travels.booking'),
        ),
    ]
