# Generated by Django 5.2.4 on 2025-08-10 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_provider_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user_2',
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(related_name='conversations', related_query_name='conversation', to=settings.AUTH_USER_MODEL),
        ),
    ]
