# Generated by Django 5.2.4 on 2025-08-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_remove_conversation_user_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='booked',
            field=models.IntegerField(default=0),
        ),
    ]
