# Generated by Django 5.2.4 on 2025-07-25 14:47

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_payment_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='province', chained_model_field='province', null=True, on_delete=django.db.models.deletion.PROTECT, to='travels.district'),
        ),
        migrations.AddField(
            model_name='place',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='places', related_query_name='place', to='travels.province'),
        ),
        migrations.AlterField(
            model_name='place',
            name='ward',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='district', chained_model_field='district', null=True, on_delete=django.db.models.deletion.PROTECT, to='travels.ward'),
        ),
    ]
