# Generated by Django 5.2.4 on 2025-09-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_alter_tour_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
