# Generated by Django 5.2.4 on 2025-07-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_place_district_place_province_alter_place_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='itineraryitem',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='tourplace',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='is_active',
            new_name='active',
        ),
    ]
