# Generated by Django 5.2.4 on 2025-09-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_place_latitude_place_longitude'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'tour')},
        ),
    ]
