# Generated by Django 5.2.4 on 2025-09-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0010_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('paid', 'Đã thanh toán'), ('canceled', 'Đã hủy'), ('rejected', 'Bị từ chối'), ('completed', 'Đã hoàn thành')], default='online', max_length=20),
        ),
    ]
