# Generated by Django 5.2.4 on 2025-09-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0011_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Thanh toán tiền mặt'), ('online', 'Ví điện tử')], default='online', max_length=20),
        ),
    ]
